import random

def encryptor(to_encrypt):
    generated_hash = []
    if len(to_encrypt) < 10:
        subst_encrypt = {
            "a": "r83WNsrpjlpEsMUzZq43",
            "b": "8Rr0aNbAvymXyt41o1We",
            "c": "0Ipj6KeLrW0LgCyLtt7b",
            "d": "IsDzQk2SHVgobRwiufSR",
            "e": "TlCgCfrIo707kg7stWC6",
            "f": "RllyHYDeCbFugrxB15Sa",
            "g": "wVQOfiwXv1OqS8miecv1",
            "h": "ADQ6i9K7HgOEbG6nNd2h",
            "i": "JzipyfAWiAgti0krrfHs",
            "j": "HyS3uYn3cMgmDo6ppqGn",
            "k": "UONdz1bvwvmW6NwNj8kh",
            "l": "omCcVZArJASFahZym6vj",
            "m": "13cC6J2D9xBI1pvOW9sq",
            "n": "swAcOwEI5j6RNq7J7X2l",
            "o": "atMLBgogK2pBfoAjHDvM",
            "p": "rhn92486Ll4L5u0bh9l7",
            "q": "wfor4ZqoFm0A7EaByttI",
            "r": "FcDMtogDsT5buvJgvYQ8",
            "s": "141CXr96V0qzJcFQeJtJ",
            "t": "tLFifj2c50BKIsibEcea",
            "u": "eYVkIJF0x9yfZJeS8PtX",
            "v": "p6JwLLML3WnrEuCvaAJH",
            "w": "D4XvrXO51rAoy9eJBjqZ",
            "x": "jYaZubA7pU0i03A5ChgE",
            "y": "08X4oPvziUZGmpttXuiT",
            "z": "XaHEBioRUXJFgqx1DtfT",
            "A": "GYoIW5lboPc2PD3AKMp3",
            "B": "ZECqsqbYk2h1m36jlStc",
            "C": "v7COHBjU3Q1EfeqGR0EG",
            "D": "qWEjbRGc2wNFM1ntmkOa",
            "E": "ebXaLGRjsvMCXpFq6UsC",
            "F": "cnyeijAh2wI3l8dCYB8Q",
            "G": "rhUrcSEYR5c2jlEIeoPt",
            "H": "xU1Ly3sD5NOicriLFhXH",
            "I": "TmhXSRhdPv7syumoFuDY",
            "J": "6enH4HTvpXs8MSBDHkB6",
            "K": "WlEZnCGmJ0fMJ0hvhvll",
            "L": "exYmYDG489KdBldRz18Q",
            "M": "UCE20MOT84y4MuRNzfBE",
            "N": "CEJADezf131X6SmFZMaV",
            "O": "arhNMSHdHC0sYgokJeov",
            "P": "1S0zp7WJgIpsSYETORby",
            "Q": "Ajh1Jm6lDXmcPY7bf6pk",
            "R": "pW08ST9Vuychw8CHVRtB",
            "S": "X0HaKd87oxSSnb4hmDJz",
            "T": "ccXdEi5Z5YUBUmTU4VLY",
            "U": "l8nQL1GfdLMHlAty4XVW",
            "V": "dNgQY0p9ZB8ITraPwAoT",
            "W": "NwLGWVVUfwaNQoRKfy00",
            "X": "gmO4Ft3nqLmqoZd2rs9G",
            "Y": "d3mRdtUjTVm4QlFl1OeS",
            "Z": "0f3aeqnTCSYxRfzTCFs9",
            ".": "jgfE75jQ9mcj73jfhqpX",
            " ": "fk375Jans92Nfjd76myU",
        }
    else:
        subst_encrypt = {
            "a": "r83WNsrpjlpEsMUzZq43",
            "b": "8Rr0aNbAvymXyt41o1We",
            "c": "0Ipj6KeLrW0LgCyLtt7b",
            "d": "IsDzQk2SHVgobRwiufSR",
            "e": "TlCgCfrIo707kg7stWC6",
            "f": "RllyHYDeCbFugrxB15Sa",
            "g": "wVQOfiwXv1OqS8miecv1",
            "h": "ADQ6i9K7HgOEbG6nNd2h",
            "i": "JzipyfAWiAgti0krrfHs",
            "j": "HyS3uYn3cMgmDo6ppqGn",
            "k": "UONdz1bvwvmW6NwNj8kh",
            "l": "omCcVZArJASFahZym6vj",
            "m": "13cC6J2D9xBI1pvOW9sq",
            "n": "swAcOwEI5j6RNq7J7X2l",
            "o": "atMLBgogK2pBfoAjHDvM",
            "p": "rhn92486Ll4L5u0bh9l7",
            "q": "wfor4ZqoFm0A7EaByttI",
            "r": "FcDMtogDsT5buvJgvYQ8",
            "s": "141CXr96V0qzJcFQeJtJ",
            "t": "tLFifj2c50BKIsibEcea",
            "u": "eYVkIJF0x9yfZJeS8PtX",
            "v": "p6JwLLML3WnrEuCvaAJH",
            "w": "D4XvrXO51rAoy9eJBjqZ",
            "x": "jYaZubA7pU0i03A5ChgE",
            "y": "08X4oPvziUZGmpttXuiT",
            "z": "XaHEBioRUXJFgqx1DtfT",
            "A": "GYoIW5lboPc2PD3AKMp3",
            "B": "ZECqsqbYk2h1m36jlStc",
            "C": "v7COHBjU3Q1EfeqGR0EG",
            "D": "qWEjbRGc2wNFM1ntmkOa",
            "E": "ebXaLGRjsvMCXpFq6UsC",
            "F": "cnyeijAh2wI3l8dCYB8Q",
            "G": "rhUrcSEYR5c2jlEIeoPt",
            "H": "xU1Ly3sD5NOicriLFhXH",
            "I": "TmhXSRhdPv7syumoFuDY",
            "J": "6enH4HTvpXs8MSBDHkB6",
            "K": "WlEZnCGmJ0fMJ0hvhvll",
            "L": "exYmYDG489KdBldRz18Q",
            "M": "UCE20MOT84y4MuRNzfBE",
            "N": "CEJADezf131X6SmFZMaV",
            "O": "arhNMSHdHC0sYgokJeov",
            "P": "1S0zp7WJgIpsSYETORby",
            "Q": "Ajh1Jm6lDXmcPY7bf6pk",
            "R": "pW08ST9Vuychw8CHVRtB",
            "S": "X0HaKd87oxSSnb4hmDJz",
            "T": "ccXdEi5Z5YUBUmTU4VLY",
            "U": "l8nQL1GfdLMHlAty4XVW",
            "V": "dNgQY0p9ZB8ITraPwAoT",
            "W": "NwLGWVVUfwaNQoRKfy00",
            "X": "gmO4Ft3nqLmqoZd2rs9G",
            "Y": "d3mRdtUjTVm4QlFl1OeS",
            "Z": "0f3aeqnTCSYxRfzTCFs9",
            ".": "jgfE75jQ9mcj73jfhqpX",
            " ": "fk375Jans92Nfjd76myU",

        }

    for char in to_encrypt:
        if char in subst_encrypt:
            generated_hash.append(subst_encrypt[char])
    return generated_hash

to_encrypt = input()
hashvar = encryptor(to_encrypt)
print(hashvar)

def decryptor(to_decrypt):
    generated_response = []
    subst_decrypt = {
        "r83WNsrpjlpEsMUzZq43": "a",
        "8Rr0aNbAvymXyt41o1We": "b",
        "0Ipj6KeLrW0LgCyLtt7b": "c",
        "IsDzQk2SHVgobRwiufSR": "d",
        "TlCgCfrIo707kg7stWC6": "e",
        "RllyHYDeCbFugrxB15Sa": "f",
        "wVQOfiwXv1OqS8miecv1": "g",
        "ADQ6i9K7HgOEbG6nNd2h": "h",
        "JzipyfAWiAgti0krrfHs": "i",
        "HyS3uYn3cMgmDo6ppqGn": "j",
        "UONdz1bvwvmW6NwNj8kh": "k",
        "omCcVZArJASFahZym6vj": "l",
        "13cC6J2D9xBI1pvOW9sq": "m",
        "swAcOwEI5j6RNq7J7X2l": "n",
        "atMLBgogK2pBfoAjHDvM": "o",
        "rhn92486Ll4L5u0bh9l7": "p",
        "wfor4ZqoFm0A7EaByttI": "q",
        "FcDMtogDsT5buvJgvYQ8": "r",
        "141CXr96V0qzJcFQeJtJ": "s",
        "tLFifj2c50BKIsibEcea": "t",
        "eYVkIJF0x9yfZJeS8PtX": "u",
        "p6JwLLML3WnrEuCvaAJH": "v",
        "D4XvrXO51rAoy9eJBjqZ": "w",
        "jYaZubA7pU0i03A5ChgE": "x",
        "08X4oPvziUZGmpttXuiT": "y",
        "XaHEBioRUXJFgqx1DtfT": "z",
        "GYoIW5lboPc2PD3AKMp3": "A",
        "ZECqsqbYk2h1m36jlStc": "B",
        "v7COHBjU3Q1EfeqGR0EG": "C",
        "qWEjbRGc2wNFM1ntmkOa": "D",
        "ebXaLGRjsvMCXpFq6UsC": "E",
        "cnyeijAh2wI3l8dCYB8Q": "F",
        "rhUrcSEYR5c2jlEIeoPt": "G",
        "xU1Ly3sD5NOicriLFhXH": "H",
        "TmhXSRhdPv7syumoFuDY": "I",
        "6enH4HTvpXs8MSBDHkB6": "J",
        "WlEZnCGmJ0fMJ0hvhvll": "K",
        "exYmYDG489KdBldRz18Q": "L",
        "UCE20MOT84y4MuRNzfBE": "M",
        "CEJADezf131X6SmFZMaV": "N",
        "arhNMSHdHC0sYgokJeov": "O",
        "1S0zp7WJgIpsSYETORby": "P",
        "Ajh1Jm6lDXmcPY7bf6pk": "Q",
        "pW08ST9Vuychw8CHVRtB": "R",
        "X0HaKd87oxSSnb4hmDJz": "S",
        "ccXdEi5Z5YUBUmTU4VLY": "T",
        "l8nQL1GfdLMHlAty4XVW": "U",
        "dNgQY0p9ZB8ITraPwAoT": "V",
        "NwLGWVVUfwaNQoRKfy00": "W",
        "gmO4Ft3nqLmqoZd2rs9G": "X",
        "d3mRdtUjTVm4QlFl1OeS": "Y",
        "0f3aeqnTCSYxRfzTCFs9": "Z",
        "jgfE75jQ9mcj73jfhqpX": ".",
        "fk375Jans92Nfjd76myU": " ",
    }
    for elem in to_decrypt:
        if elem in subst_decrypt:
            generated_response.append(subst_decrypt[elem])
    return generated_response

unhashed = decryptor(hashvar)
print(unhashed)
